// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/Monstergogo/beauty-share/internal/service_interface"
)

// Injectors from wire.go:

func GetOssServer() service_interface.OSSService {
	ossService := service_interface.OssServiceProvider()
	return ossService
}
