// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/Monstergogo/beauty-share/internal/repo_interface"
	"github.com/Monstergogo/beauty-share/internal/service_interface"
)

// Injectors from wire.go:

func GetOssServer() service_interface.OSSService {
	ossService := service_interface.OssServiceProvider()
	return ossService
}

func GetShareServer() service_interface.ShareService {
	client := repo_interface.MongoDBClientProvider()
	mongoRepo := repo_interface.MongoRepoProvider(client)
	shareService := service_interface.ShareServiceProvider(mongoRepo)
	return shareService
}
